local Library = {}

function Library:CreateWindow(title)
    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = "AutoGeneratedUI"
    
    -- Gelişmiş Executor Korunumu (CoreGui Entegrasyonu)
    local targetParent = game:GetService("CoreGui")
    pcall(function()
        if gethui then targetParent = gethui() end
    end)
    ScreenGui.Parent = targetParent

    -- Ana Panel
    local MainFrame = Instance.new("Frame", ScreenGui)
    MainFrame.Size = UDim2.new(0, 350, 0, 450)
    MainFrame.Position = UDim2.new(0.5, -175, 0.5, -225)
    MainFrame.BackgroundColor3 = _G.LibraryTheme.MainBg
    MainFrame.Active = true
    MainFrame.Draggable = true -- Sürükleme desteği

    -- Başlık Alanı
    local Title = Instance.new("TextLabel", MainFrame)
    Title.Size = UDim2.new(1, 0, 0, 40)
    Title.Text = title
    Title.TextColor3 = _G.LibraryTheme.TextColor
    Title.BackgroundColor3 = _G.LibraryTheme.ElementBg
    Title.Font = _G.LibraryTheme.Font
    Title.TextSize = 16

    -- İçerik Taşıyıcı Frame
    local ContentFrame = Instance.new("Frame", MainFrame)
    ContentFrame.Size = UDim2.new(1, 0, 1, -40)
    ContentFrame.Position = UDim2.new(0, 0, 0, 40)
    ContentFrame.BackgroundTransparency = 1

    -- UI Elementlerini Pencereye Bağlama Fonksiyonları
    function MainFrame:CreateButton(text, callback)
        if _G.ButtonComponent then
            return _G.ButtonComponent.New(ContentFrame, text, callback)
        else
            -- Eğer Actions henüz çalışmadıysa veya hata oluştuysa yedek fallback:
            local fallbackBtn = Instance.new("TextButton", ContentFrame)
            fallbackBtn.Size = UDim2.new(0.9, 0, 0, 35)
            fallbackBtn.Text = text
            fallbackBtn.MouseButton1Click:Connect(callback)
            return fallbackBtn
        end
    end

    return MainFrame
end

return Library

